name: tractian_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.2
  provider: ^6.1.2
  get_it: ^7.7.0
  super_sliver_list: ^0.4.1
  string_similarity: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  
  assets:
  - assets/LOGOTRACTIAN.png
  - assets/icons/homeicon.png
  - assets/icons/criticalIcon.png
  - assets/icons/energyIcon.png
  - assets/icons/GoLocation.png
  - assets/icons/component.png
  - assets/icons/asset.png
  